#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 image_dir thumb_dir";
  exit
fi

cat << EOF
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$1</title>
    <link rel='stylesheet' href='css/lightgallery.min.css'>
  </head>
  <body bgcolor=black>
    <div id='links'>
EOF

cd $1
ls *.jpg | while read f; do
  echo "      <a href='$1/$f' title='$f'>"
  echo "        <img src='$2/$f' alt='$f'>"
  echo "      </a>"
done

cat << EOF2
    </div>
    <script src="js/lightgallery.min.js"></script>
    <script src="js/lg-thumbnail.js"></script>
    <script src="js/lg-zoom.js"></script>
    <script src="js/lg-autoplay.js"></script>
    <script src="js/lg-hash.js"></script>
    <script src="js/lg-thumbnail.js"></script>
    <script>
      lightGallery(document.getElementById('links'), {thumbnail: true});
    </script>
  </body>
</html>
EOF2
